version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./MERN-Crud-Backend
    container_name: mern-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/merncrud
      - JWT_SECRET_KEY=YourKey
      - PORT=5000
    depends_on:
      - mongo

  frontend:
    build: ./MERN-Cru-Frontend
    container_name: mern-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:5000/api
    depends_on:
      - backend

volumes:
  mongo-data:
